### ISSUE TITLE
Add ability to pass funcMaps

### ISSUE THREAD

**Issue by abnvanand** [thediveo/klo#6]
Go text/template allows providing a map of functions when creating a template.
See: https://pkg.go.dev/text/template#FuncMap

Is it possible to add the ability to pass this funcMap maybe when creating a klo.Spec?
These functions could then be used in tmpl file and passed as GoTemplateArg to klo.

**Comment by thediveo** [comment]
Makes sense, I highly appreciate it! We just need to keep the v1 compatibility. Thank your very much also for the associated PR!

**Comment by thediveo** [comment]
merged and release in v1.1.0. Thank you very much!
